### ISSUE TITLE
Committed transactions are regarded as pending

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#163]
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/f045c880-325a-41af-965b-4f5cf60b61a3)

This issue is found in pre-release version, but also reported from users in published versions

```
[2023-05-28 18:37:37.781] [warn]  API Controller:	channel handling error: TypeError: Cannot read properties of undefined (reading 'startsWith') TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Neuron.app/Contents/Resources/app.asar/dist/controllers/wallets.js:35:44
    at Array.forEach (<anonymous>)
    at WalletsController.checkAddresses (Neuron.app/Contents/Resources/app.asar/dist/controllers/wallets.js:31:23)
    at WalletsController.generateTx (Neuron.app/Contents/Resources/app.asar/dist/controllers/wallets.js:337:14)
    at Neuron.app/Contents/Resources/app.asar/dist/controllers/api.js:264:92
    at Neuron.app/Contents/Resources/app.asar/dist/controllers/api.js:556:39
    at node:electron/js2c/browser_init:2:97961
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81474)
    at EventEmitter.emit (node:events:513:28)
```

**Comment by Keith-CY** [comment]
The status of transaction became correct after restarting

**Comment by Keith-CY** [comment]
This case is invalid, because Neuron hadn't reached the block number where the transaction is in
