### ISSUE TITLE
SQLite Error

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#376]
Neuron Version: 0.114.2

Error:
```
[2024-04-03T05:53:19.397Z] [error] SQLITE_ERROR: near "s": syntax error
[2024-04-03T05:53:19.643Z] [error] SQLITE_ERROR: near "s": syntax error
```

Behavior:
No matter which wallet is active, the address list doesn't change. And the address format is the deprecated one.

Addresses are possibly cached in local storage and not updated because SQLite is broken.

After importing a new wallet, the error appears again.

After removing `%AppData/Neuron/Local Storage/leveldb` and restarting Neuron, Neuron stays on the `create a new wallet` page even though there are some wallets.

Try to import the wallet again and get
![image](https://github.com/Magickbase/neuron-public-issues/assets/7271329/57af7934-cc89-4650-97a8-da83148d00b5)

**Comment by silySuper** [comment]
My neuron version,I have switched between different walllets,and the address has changed.

<img width="289" alt="截屏2024-04-03 15 00 52" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/13295aec-8fbf-4432-adc4-d0f7fea0d5ba">

Another error in log shows:
ERROR panic  thread 'ChainService' panicked at 'db operation should be ok: Error { kind: Internal, inner: Database(Corruption: block checksum mismatch: stored = 67350105, computed = 4050139833, type = 4  in /Volumes/My Passport/ckb节点/ckb_v0.108.1_x86_64-apple-darwin-portable/testnet/data/db/209036.sst offset 4338299 size 2939) }': store/src/transaction.rs:49   0: backtrace::capture::Backtrace::new
   1: ckb_logger_service::setup_panic_logger::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: ckb_reward_calculator::RewardCalculator<CS>::block_reward_internal
   9: ckb_verification_contextual::contextual_block_verifier::ContextualBlockVerifier<CS,MS>::verify
  10: ckb_chain::chain::ChainService::reconcile_main_chain
  11: ckb_chain::chain::ChainService::insert_block
  12: ckb_chain::chain::ChainService::process_block
  13: ckb_chain::chain::ChainService::start::{{closure}}
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: std::sys::unix::thread::Thread::new::thread_start
  17: __pthread_joiner_wake
I do not know whether it is related to this problem.

**Comment by devchenyan** [comment]
The logs show ’SQLITE_MISUSE‘ in 2022, not related to this version upgrade. After removing the local cache and reinstalling neuron, it works fine.

```
[2021-08-26 20:20:14.832] [info] Database:	saved synced block #4262459
[2021-08-27 00:10:29.892] [info] Database:	saved synced block #4263460
[2021-08-27 09:01:33.803] [info] CKB:	killing node
[2022-02-18 09:28:16.941] [error] Network:	fail to connect to the network. Is CKB node running?
[2022-02-18 09:28:17.728] [error] SQLITE_ERROR: near "s": syntax error
[2022-02-18 09:28:17.728] [info] Network:	switched to: {
  id: 'mainnet',
  name: 'default node',
  remote: 'http://localhost:8114',
  genesisHash: '0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5',
  type: 0,
  chain: 'ckb'
}
[2022-02-18 09:28:17.734] [error] {
  constructor: 'QueryFailedError',
  message: 'SQLITE_MISUSE: Database is closed',
  errno: 21,
  code: 'SQLITE_MISUSE',
  name: 'QueryFailedError',
  query: 'SELECT "HdPublicKeyInfo"."id" AS "HdPublicKeyInfo_id", "HdPublicKeyInfo"."walletId" AS "HdPublicKeyInfo_walletId", "HdPublicKeyInfo"."addressType" AS "HdPublicKeyInfo_addressType", "HdPublicKeyInfo"."addressIndex" AS "HdPublicKeyInfo_addressIndex", "HdPublicKeyInfo"."publicKeyInBlake160" AS "HdPublicKeyInfo_publicKeyInBlake160", "HdPublicKeyInfo"."createdAt" AS "HdPublicKeyInfo_createdAt" FROM "hd_public_key_info" "HdPublicKeyInfo" WHERE "HdPublicKeyInfo"."walletId" = ?',
  parameters: [ '32f97ca9-8012-4d37-9a03-a1f64fbabce7' ],
  stack: 'QueryFailedError: SQLITE_MISUSE: Database is closed\n' +
    '    at new QueryFailedError (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\typeorm\\error\\QueryFailedError.js:11:28)\n' +
    '    at handler (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\typeorm\\driver\\sqlite\\SqliteQueryRunner.js:48:38)\n' +
    '    at replacement (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\sqlite3\\lib\\trace.js:19:31)\n' +
    '    at Database.errBack (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\sqlite3\\lib\\sqlite3.js:16:21)\n' +
    '    at Database.<anonymous> (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\sqlite3\\lib\\sqlite3.js:20:25)\n' +
    '    at Database.object.<computed> [as all] (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\sqlite3\\lib\\trace.js:31:20)\n' +
    '    at SqliteQueryRunner.<anonymous> (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\typeorm\\driver\\sqlite\\SqliteQueryRunner.js:64:48)\n' +
    '    at step (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\tslib\\tslib.js:136:27)\n' +
    '    at Object.next (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\tslib\\tslib.js:117:57)\n' +
    '    at fulfilled (C:\\Users\\xiangmei\\AppData\\Local\\Programs\\Neuron\\resources\\app.asar\\node_modules\\tslib\\tslib.js:107:62)'
}
[2022-02-18 09:28:18.472] [warn] channel handling error: QueryFailedError: SQLITE_MISUSE: Database is closed QueryFailedError: SQLITE_MISUSE: Database is closed
    at new QueryFailedError (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at handler (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:48:38)
    at replacement (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\trace.js:19:31)
    at Database.errBack (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js:16:21)
    at Database.<anonymous> (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js:20:25)
    at Database.object.<computed> [as all] (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\trace.js:31:20)
    at SqliteQueryRunner.<anonymous> (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:64:48)
    at step (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\tslib\tslib.js:117:57)
    at fulfilled (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\tslib\tslib.js:107:62)
[2022-02-18 09:28:18.838] [warn] channel handling error: QueryFailedError: SQLITE_MISUSE: Database is closed QueryFailedError: SQLITE_MISUSE: Database is closed
    at new QueryFailedError (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at handler (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:48:38)
    at replacement (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\trace.js:19:31)
    at Database.errBack (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js:16:21)
    at Database.<anonymous> (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js:20:25)
    at Database.object.<computed> [as all] (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\sqlite3\lib\trace.js:31:20)
    at SqliteQueryRunner.<anonymous> (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:64:48)
    at step (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\tslib\tslib.js:117:57)
    at fulfilled (C:\Users\xiangmei\AppData\Local\Programs\Neuron\resources\app.asar\node_modules\tslib\tslib.js:107:62)
[2022-02-18 09:28:18.877] [warn] channel handling error: QueryFailedError: SQLITE_MISUSE: Database is closed QueryFailedError: SQLITE_MISUSE: Database is closed
```

![image](https://github.com/Magickbase/neuron-public-issues/assets/11756869/9ad1763f-75f0-4248-942f-4ba646020c30)

**Comment by Danie0918** [comment]
Resolved.

Related issue:https://github.com/nervosnetwork/neuron/issues/3065
