### ISSUE TITLE
Testnet sync is stay connecting

### ISSUE THREAD

**Issue by silySuper** [Magickbase/neuron-public-issues#382]
I have start a testnet node locally，but sync progress is stay connecting.

<img width="705" alt="截屏2024-04-12 10 35 02" src="https://github.com/nervosnetwork/neuron/assets/25971273/57db88dd-d9dd-4ec1-bd30-3b02303d0930">

<img width="707" alt="截屏2024-04-12 10 35 32" src="https://github.com/nervosnetwork/neuron/assets/25971273/46296163-ac9b-4c3a-bc65-11c26d261dc9">
<img width="463" alt="截屏2024-04-12 10 35 13" src="https://github.com/nervosnetwork/neuron/assets/25971273/93a3aedf-7429-4322-9a53-eac5c8b1c2ca">
<img width="708" alt="截屏2024-04-12 10 35 22" src="https://github.com/nervosnetwork/neuron/assets/25971273/0a5735fa-aa98-4dc6-8555-23d203b754c3">

[main.log](https://github.com/nervosnetwork/neuron/files/14953372/main.log)

Is it that the port related to this problem?

**Comment by yanguoyu** [comment]
Hi, @silySuper Here is the log.
```
[2024-04-12T02:12:04.553Z] [warn]  API Controller:	channel handling error: TypeError: fetch failed TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at async FullCKBRPC.localNodeInfo (~/Downloads/Neuron 2.app/Contents/Resources/app/node_modules/@ckb-lumos/rpc/lib/method.js:57:19)
    at async CommonUtils.retry (~/Downloads/Neuron 2.app/Contents/Resources/app/dist/utils/common.js:17:16)
    at async NodeService.verifyExternalCkbNode (~/Downloads/Neuron 2.app/Contents/Resources/app/dist/services/node.js:181:35)
    at async ~/Downloads/Neuron 2.app/Contents/Resources/app/dist/controllers/api.js:201:29
    at async ~/Downloads/Neuron 2.app/Contents/Resources/app/dist/controllers/api.js:620:33
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86716)
```

Could you try to call the RPC `localNodeInfo` and ensure that rpc returns normal?

**Comment by silySuper** [comment]
> Hi, @silySuper Here is the log.
> 
> ```
> [2024-04-12T02:12:04.553Z] [warn]  API Controller:	channel handling error: TypeError: fetch failed TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11372:11)
>     at async FullCKBRPC.localNodeInfo (~/Downloads/Neuron 2.app/Contents/Resources/app/node_modules/@ckb-lumos/rpc/lib/method.js:57:19)
>     at async CommonUtils.retry (~/Downloads/Neuron 2.app/Contents/Resources/app/dist/utils/common.js:17:16)
>     at async NodeService.verifyExternalCkbNode (~/Downloads/Neuron 2.app/Contents/Resources/app/dist/services/node.js:181:35)
>     at async ~/Downloads/Neuron 2.app/Contents/Resources/app/dist/controllers/api.js:201:29
>     at async ~/Downloads/Neuron 2.app/Contents/Resources/app/dist/controllers/api.js:620:33
>     at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86716)
> ```
> 
> Could you try to call the RPC `localNodeInfo` and ensure that rpc returns normal?
<img width="1076" alt="截屏2024-04-12 16 04 36" src="https://github.com/Magickbase/neuron-public-issues/assets/25971273/4cb6fdaa-2eaa-4179-9a17-df0855c3a1d1">

**Comment by silySuper** [comment]
I hav tried situations:
1.start v0.113 in local ,and run new data,sync successfully✅
2.start v0.113 in local ,and run v108 old  data(which testnet data file is in portable hard disk)，node start fail.Because ❌


![Image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/ce154d3c-d0fa-4331-93e7-a289946e756e)


3.start v0.114(which node file is in portable hard disk) in local, and run new data,sync successfully,✅
4.start v0.114 in local,and run new data,sync successfully,✅
5.start v0.114(which node file is in portable hard disk) in local, and run v108 old  data(which testnet data file is in portable hard disk) ,sync fail .❌


![Image](https://github.com/Magickbase/neuron-public-issues/assets/25971273/62487ec9-2844-4ff6-93fd-616c7ade3a36)



[main.log](https://github.com/Magickbase/neuron-public-issues/files/15004608/main.log)

**Comment by Danie0918** [comment]
Still troubleshooting the cause, please comment with any updates. @yanguoyu @silySuper

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/3143
