### ISSUE TITLE
Some modules are incompatible with arm64

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/neuron-public-issues#81]
```
Uncaught Exception:
Error: dlopen(/var/folders/nm/r1twtwkj2y1c28hn4jmrst400000gn/T/.com.nervos.neuron.2hSmGj, 0x0001): tried: '/var/folders/nm/r1twtwkj2y1c28hn4jmrst400000gn/T/.com.nervos.neuron.2hSmGj' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/private/var/folders/nm/r1twtwkj2y1c28hn4jmrst400000gn/T/.com.nervos.neuron.2hSmGj' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:94:18)
at load (/private/var/folders/nm/r1twtwkj2y1c28hn4jmrst400000gn/T/AppTranslocation/57F36292-8347-4EA5-9CEA-15E91652B4EB/d/Neuron.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:22:10)
at Object.<anonymous> (/private/var/folders/nm/r1twtwkj2y1c28hn4jmrst400000gn/T/AppTranslocation/57F36292-8347-4EA5-9CEA-15E91652B4EB/d/Neuron.app/Contents/Resources/app.asar/node_modules/usb/usb.js:1:63)
```

This exception is thrown when running Neuron(packaged by https://github.com/nervosnetwork/neuron/actions/runs/3613718957) on MacOS 12.5, M1 Max chip.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2541

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2542
